name: LimSujung
author: LimSujung
baseurl: 
description: theme for jekyll
github: https://github.com/karreee28
# twitter: http://www.twitter.com/
# facebook: http://www.facebook.com
# linkedin: http://www.linkedin.com
email: gguru204@gmail.com
location: Osan
disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.


highlighter: rouge
markdown: kramdown
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
